import { create } from 'zustand';

export const useStore = create((set) => ({
  sessionId: crypto.randomUUID(),
  pdfs: [],
  issues: [],
  metrics: { docs: 0, complete: 0, incomplete: 0, inferred: 0 },
  globalProg: { done: 0, total: 0, elapsed: 0, eta: 0, paused: false },
  fileProg: { done: 0, total: 0, filename: '' },
  logs: [],
  aiLogs: [],
  scanLine: null,
  spinFrame: 0,
  
  status: 'idle',
  selectedIssue: null,
  correctCurr: '',
  correctTot: '',
  selectedPdfFilter: '',
  selectedPdfPath: '',
  showHistory: false,
  historySessions: [],
  confirmModal: { isOpen: false, title: '', message: '', onConfirm: null, isAlert: false },
  showTerminal: true,
  aiLogMode: false,
  showAllIssues: false,
  cascadeToast: null,

  // Universal updaters to mimic useState behavior seamlessly
  setSessionId: (val) => set(s => ({ sessionId: typeof val === 'function' ? val(s.sessionId) : val })),
  setPdfs: (val) => set(s => ({ pdfs: typeof val === 'function' ? val(s.pdfs) : val })),
  setIssues: (val) => set(s => ({ issues: typeof val === 'function' ? val(s.issues) : val })),
  setMetrics: (val) => set(s => ({ metrics: typeof val === 'function' ? val(s.metrics) : val })),
  setGlobalProg: (val) => set(s => ({ globalProg: typeof val === 'function' ? val(s.globalProg) : val })),
  setFileProg: (val) => set(s => ({ fileProg: typeof val === 'function' ? val(s.fileProg) : val })),
  setLogs: (val) => set(s => ({ logs: typeof val === 'function' ? val(s.logs) : val })),
  setAiLogs: (val) => set(s => ({ aiLogs: typeof val === 'function' ? val(s.aiLogs) : val })),
  setScanLine: (val) => set(s => ({ scanLine: typeof val === 'function' ? val(s.scanLine) : val })),
  setSpinFrame: (val) => set(s => ({ spinFrame: typeof val === 'function' ? val(s.spinFrame) : val })),
  setStatus: (val) => set(s => ({ status: typeof val === 'function' ? val(s.status) : val })),
  setSelectedIssue: (val) => set(s => ({ selectedIssue: typeof val === 'function' ? val(s.selectedIssue) : val })),
  setCorrectCurr: (val) => set(s => ({ correctCurr: typeof val === 'function' ? val(s.correctCurr) : val })),
  setCorrectTot: (val) => set(s => ({ correctTot: typeof val === 'function' ? val(s.correctTot) : val })),
  setSelectedPdfFilter: (val) => set(s => ({ selectedPdfFilter: typeof val === 'function' ? val(s.selectedPdfFilter) : val })),
  setSelectedPdfPath: (val) => set(s => ({ selectedPdfPath: typeof val === 'function' ? val(s.selectedPdfPath) : val })),
  setShowHistory: (val) => set(s => ({ showHistory: typeof val === 'function' ? val(s.showHistory) : val })),
  setHistorySessions: (val) => set(s => ({ historySessions: typeof val === 'function' ? val(s.historySessions) : val })),
  setConfirmModal: (val) => set(s => ({ confirmModal: typeof val === 'function' ? val(s.confirmModal) : val })),
  setShowTerminal: (val) => set(s => ({ showTerminal: typeof val === 'function' ? val(s.showTerminal) : val })),
  setAiLogMode: (val) => set(s => ({ aiLogMode: typeof val === 'function' ? val(s.aiLogMode) : val })),
  setShowAllIssues: (val) => set(s => ({ showAllIssues: typeof val === 'function' ? val(s.showAllIssues) : val })),
  setCascadeToast: (val) => set(s => ({ cascadeToast: typeof val === 'function' ? val(s.cascadeToast) : val })),
}));
